name: 'C++ CI'

on:
  push:
    branches:
      - '*'
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-system-dev \
            libboost-test-dev \
            libboost-program-options-dev \
            build-essential \
            cmake \
            dpkg-dev

      - name: Configure CMake
        run: |
          cmake . \
            -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu \
            -DPATCH_VERSION=${{ github.run_number }} \
            -DWITH_BOOST_TEST=ON

      - name: Build
        run: |
          cmake --build . --config Release

      - name: Run tests
        run: ctest --output-on-failure

      - name: Create packages
        run: |
          cmake --build . --target package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.0.${{ github.run_number }}
          release_name: Release v0.0.${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Library DEB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib_join_server_0.0.${{ github.run_number }}_amd64.deb
          asset_name: lib_join_server_0.0.${{ github.run_number }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Join Server DEB
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./join_server_0.0.${{ github.run_number }}_amd64.deb
          asset_name: join_server_0.0.${{ github.run_number }}_amd64.deb
          asset_content_type: application/vnd.debian.binary-package